name: bible_osterwald
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  video_player: ^0.8.0
  shared_preferences: "^0.4.2"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/bible_PNG33.png
    - assets/images/bible_PNG28.png
    - assets/images/bible_PNG47.png
  fonts:
    - family: Elegant
      fonts:
        - asset: assets/fonts/elegant/Elegant.ttf
    - family: Sanford
      fonts:
        - asset: assets/fonts/sanford/SANFW___.TTF